# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'd_ImageCollector.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGroupBox, QLabel, QMainWindow, QPlainTextEdit,
    QPushButton, QSizePolicy, QSlider, QStatusBar,
    QTabWidget, QWidget)

class Ui_ImageCollector(object):
    def setupUi(self, ImageCollector):
        if not ImageCollector.objectName():
            ImageCollector.setObjectName(u"ImageCollector")
        ImageCollector.resize(1330, 628)
        self.centralwidget = QWidget(ImageCollector)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(1090, 445, 49, 16))
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(1070, 5, 16, 601))
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QRect(1090, 5, 231, 401))
        self.camera_tab = QWidget()
        self.camera_tab.setObjectName(u"camera_tab")
        self.camera_swich_combo_box = QComboBox(self.camera_tab)
        self.camera_swich_combo_box.setObjectName(u"camera_swich_combo_box")
        self.camera_swich_combo_box.setGeometry(QRect(90, 10, 131, 21))
        self.label_2 = QLabel(self.camera_tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 10, 61, 20))
        self.label_2.setAlignment(Qt.AlignCenter)
        self.save_photo_button = QPushButton(self.camera_tab)
        self.save_photo_button.setObjectName(u"save_photo_button")
        self.save_photo_button.setEnabled(True)
        self.save_photo_button.setGeometry(QRect(10, 50, 211, 31))
        self.save_photo_button.setCheckable(False)
        self.auto_mark_edges_checkbox = QCheckBox(self.camera_tab)
        self.auto_mark_edges_checkbox.setObjectName(u"auto_mark_edges_checkbox")
        self.auto_mark_edges_checkbox.setEnabled(True)
        self.auto_mark_edges_checkbox.setGeometry(QRect(10, 120, 201, 31))
        self.auto_mark_edges_checkbox.setCheckable(True)
        self.new_coin_button = QPushButton(self.camera_tab)
        self.new_coin_button.setObjectName(u"new_coin_button")
        self.new_coin_button.setEnabled(True)
        self.new_coin_button.setGeometry(QRect(10, 90, 211, 31))
        self.camera_blur_kernel_slider = QSlider(self.camera_tab)
        self.camera_blur_kernel_slider.setObjectName(u"camera_blur_kernel_slider")
        self.camera_blur_kernel_slider.setGeometry(QRect(89, 160, 131, 10))
        self.camera_blur_kernel_slider.setMinimum(3)
        self.camera_blur_kernel_slider.setMaximum(50)
        self.camera_blur_kernel_slider.setOrientation(Qt.Horizontal)
        self.label_5 = QLabel(self.camera_tab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 160, 71, 10))
        self.camera_blur_sigma_slider = QSlider(self.camera_tab)
        self.camera_blur_sigma_slider.setObjectName(u"camera_blur_sigma_slider")
        self.camera_blur_sigma_slider.setGeometry(QRect(90, 180, 131, 10))
        self.camera_blur_sigma_slider.setMinimum(2)
        self.camera_blur_sigma_slider.setMaximum(30)
        self.camera_blur_sigma_slider.setOrientation(Qt.Horizontal)
        self.camera_canny_thr_1_slider = QSlider(self.camera_tab)
        self.camera_canny_thr_1_slider.setObjectName(u"camera_canny_thr_1_slider")
        self.camera_canny_thr_1_slider.setGeometry(QRect(90, 200, 131, 10))
        self.camera_canny_thr_1_slider.setMinimum(50)
        self.camera_canny_thr_1_slider.setMaximum(500)
        self.camera_canny_thr_1_slider.setOrientation(Qt.Horizontal)
        self.camera_canny_thr_2_slider = QSlider(self.camera_tab)
        self.camera_canny_thr_2_slider.setObjectName(u"camera_canny_thr_2_slider")
        self.camera_canny_thr_2_slider.setGeometry(QRect(90, 220, 131, 10))
        self.camera_canny_thr_2_slider.setMinimum(9)
        self.camera_canny_thr_2_slider.setMaximum(500)
        self.camera_canny_thr_2_slider.setOrientation(Qt.Horizontal)
        self.camera_dilate_1_slider = QSlider(self.camera_tab)
        self.camera_dilate_1_slider.setObjectName(u"camera_dilate_1_slider")
        self.camera_dilate_1_slider.setGeometry(QRect(90, 240, 131, 10))
        self.camera_dilate_1_slider.setMinimum(4)
        self.camera_dilate_1_slider.setMaximum(50)
        self.camera_dilate_1_slider.setOrientation(Qt.Horizontal)
        self.camera_dilate_2_slider = QSlider(self.camera_tab)
        self.camera_dilate_2_slider.setObjectName(u"camera_dilate_2_slider")
        self.camera_dilate_2_slider.setGeometry(QRect(90, 260, 131, 10))
        self.camera_dilate_2_slider.setMinimum(2)
        self.camera_dilate_2_slider.setMaximum(50)
        self.camera_dilate_2_slider.setOrientation(Qt.Horizontal)
        self.camera_erode_1_slider = QSlider(self.camera_tab)
        self.camera_erode_1_slider.setObjectName(u"camera_erode_1_slider")
        self.camera_erode_1_slider.setGeometry(QRect(90, 280, 131, 10))
        self.camera_erode_1_slider.setMinimum(13)
        self.camera_erode_1_slider.setMaximum(50)
        self.camera_erode_1_slider.setOrientation(Qt.Horizontal)
        self.label_6 = QLabel(self.camera_tab)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 180, 71, 10))
        self.label_7 = QLabel(self.camera_tab)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 200, 71, 10))
        self.label_8 = QLabel(self.camera_tab)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 220, 71, 10))
        self.label_9 = QLabel(self.camera_tab)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 240, 71, 10))
        self.label_10 = QLabel(self.camera_tab)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 260, 71, 10))
        self.label_11 = QLabel(self.camera_tab)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 280, 71, 10))
        self.camera_erode_2_slider = QSlider(self.camera_tab)
        self.camera_erode_2_slider.setObjectName(u"camera_erode_2_slider")
        self.camera_erode_2_slider.setGeometry(QRect(90, 300, 131, 10))
        self.camera_erode_2_slider.setMinimum(7)
        self.camera_erode_2_slider.setMaximum(50)
        self.camera_erode_2_slider.setOrientation(Qt.Horizontal)
        self.label_12 = QLabel(self.camera_tab)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 300, 71, 10))
        self.camera_dilate_iter_slider = QSlider(self.camera_tab)
        self.camera_dilate_iter_slider.setObjectName(u"camera_dilate_iter_slider")
        self.camera_dilate_iter_slider.setGeometry(QRect(90, 320, 131, 10))
        self.camera_dilate_iter_slider.setMinimum(11)
        self.camera_dilate_iter_slider.setMaximum(40)
        self.camera_dilate_iter_slider.setOrientation(Qt.Horizontal)
        self.camera_erode_iter_slider = QSlider(self.camera_tab)
        self.camera_erode_iter_slider.setObjectName(u"camera_erode_iter_slider")
        self.camera_erode_iter_slider.setGeometry(QRect(90, 340, 131, 10))
        self.camera_erode_iter_slider.setMinimum(4)
        self.camera_erode_iter_slider.setMaximum(50)
        self.camera_erode_iter_slider.setOrientation(Qt.Horizontal)
        self.label_13 = QLabel(self.camera_tab)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 320, 71, 10))
        self.label_14 = QLabel(self.camera_tab)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 340, 71, 10))
        self.tabWidget.addTab(self.camera_tab, "")
        self.gallery_tab = QWidget()
        self.gallery_tab.setObjectName(u"gallery_tab")
        self.next_gallery_photo_button = QPushButton(self.gallery_tab)
        self.next_gallery_photo_button.setObjectName(u"next_gallery_photo_button")
        self.next_gallery_photo_button.setGeometry(QRect(120, 10, 101, 31))
        self.previous_gallery_photo_button = QPushButton(self.gallery_tab)
        self.previous_gallery_photo_button.setObjectName(u"previous_gallery_photo_button")
        self.previous_gallery_photo_button.setGeometry(QRect(10, 10, 91, 31))
        self.line = QFrame(self.gallery_tab)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 60, 201, 16))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.redraw_coin_contour_checkbox = QCheckBox(self.gallery_tab)
        self.redraw_coin_contour_checkbox.setObjectName(u"redraw_coin_contour_checkbox")
        self.redraw_coin_contour_checkbox.setGeometry(QRect(10, 50, 201, 20))
        self.contour_correction_container = QGroupBox(self.gallery_tab)
        self.contour_correction_container.setObjectName(u"contour_correction_container")
        self.contour_correction_container.setEnabled(False)
        self.contour_correction_container.setGeometry(QRect(10, 70, 201, 301))
        self.save_cropped_image_button = QPushButton(self.contour_correction_container)
        self.save_cropped_image_button.setObjectName(u"save_cropped_image_button")
        self.save_cropped_image_button.setGeometry(QRect(0, 270, 201, 31))
        self.automatic_contour_detextion_checkbox = QCheckBox(self.contour_correction_container)
        self.automatic_contour_detextion_checkbox.setObjectName(u"automatic_contour_detextion_checkbox")
        self.automatic_contour_detextion_checkbox.setGeometry(QRect(10, 0, 181, 21))
        self.manual_contour_reset_button = QPushButton(self.contour_correction_container)
        self.manual_contour_reset_button.setObjectName(u"manual_contour_reset_button")
        self.manual_contour_reset_button.setGeometry(QRect(0, 240, 201, 31))
        self.gallery_dilate_2_slider = QSlider(self.contour_correction_container)
        self.gallery_dilate_2_slider.setObjectName(u"gallery_dilate_2_slider")
        self.gallery_dilate_2_slider.setGeometry(QRect(69, 90, 101, 22))
        self.gallery_dilate_2_slider.setMinimum(2)
        self.gallery_dilate_2_slider.setMaximum(50)
        self.gallery_dilate_2_slider.setOrientation(Qt.Horizontal)
        self.gallery_erode_1_slider = QSlider(self.contour_correction_container)
        self.gallery_erode_1_slider.setObjectName(u"gallery_erode_1_slider")
        self.gallery_erode_1_slider.setGeometry(QRect(69, 120, 101, 22))
        self.gallery_erode_1_slider.setMinimum(13)
        self.gallery_erode_1_slider.setMaximum(50)
        self.gallery_erode_1_slider.setOrientation(Qt.Horizontal)
        self.gallery_erode_2_slider = QSlider(self.contour_correction_container)
        self.gallery_erode_2_slider.setObjectName(u"gallery_erode_2_slider")
        self.gallery_erode_2_slider.setGeometry(QRect(69, 150, 101, 22))
        self.gallery_erode_2_slider.setMinimum(7)
        self.gallery_erode_2_slider.setMaximum(50)
        self.gallery_erode_2_slider.setOrientation(Qt.Horizontal)
        self.gallery_dilate_iter_slider = QSlider(self.contour_correction_container)
        self.gallery_dilate_iter_slider.setObjectName(u"gallery_dilate_iter_slider")
        self.gallery_dilate_iter_slider.setGeometry(QRect(69, 180, 101, 22))
        self.gallery_dilate_iter_slider.setMinimum(11)
        self.gallery_dilate_iter_slider.setMaximum(40)
        self.gallery_dilate_iter_slider.setOrientation(Qt.Horizontal)
        self.gallery_erode_iter_slider = QSlider(self.contour_correction_container)
        self.gallery_erode_iter_slider.setObjectName(u"gallery_erode_iter_slider")
        self.gallery_erode_iter_slider.setGeometry(QRect(69, 210, 101, 22))
        self.gallery_erode_iter_slider.setMinimum(4)
        self.gallery_erode_iter_slider.setMaximum(50)
        self.gallery_erode_iter_slider.setOrientation(Qt.Horizontal)
        self.gallery_dilate_1_slider = QSlider(self.contour_correction_container)
        self.gallery_dilate_1_slider.setObjectName(u"gallery_dilate_1_slider")
        self.gallery_dilate_1_slider.setGeometry(QRect(69, 60, 101, 22))
        self.gallery_dilate_1_slider.setMinimum(4)
        self.gallery_dilate_1_slider.setMaximum(50)
        self.gallery_dilate_1_slider.setOrientation(Qt.Horizontal)
        self.gallery_blur_kernel_slider = QSlider(self.contour_correction_container)
        self.gallery_blur_kernel_slider.setObjectName(u"gallery_blur_kernel_slider")
        self.gallery_blur_kernel_slider.setGeometry(QRect(69, 30, 101, 22))
        self.gallery_blur_kernel_slider.setMinimum(3)
        self.gallery_blur_kernel_slider.setMaximum(50)
        self.gallery_blur_kernel_slider.setOrientation(Qt.Horizontal)
        self.label_15 = QLabel(self.contour_correction_container)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 30, 41, 21))
        self.label_16 = QLabel(self.contour_correction_container)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 60, 51, 16))
        self.label_17 = QLabel(self.contour_correction_container)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 90, 51, 16))
        self.label_18 = QLabel(self.contour_correction_container)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 120, 51, 16))
        self.label_19 = QLabel(self.contour_correction_container)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 150, 51, 16))
        self.label_20 = QLabel(self.contour_correction_container)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 180, 51, 16))
        self.label_21 = QLabel(self.contour_correction_container)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 210, 51, 16))
        self.tabWidget.addTab(self.gallery_tab, "")
        self.coin_tab = QWidget()
        self.coin_tab.setObjectName(u"coin_tab")
        self.remove_coin_button = QPushButton(self.coin_tab)
        self.remove_coin_button.setObjectName(u"remove_coin_button")
        self.remove_coin_button.setGeometry(QRect(10, 60, 201, 41))
        self.change_coin_params_button = QPushButton(self.coin_tab)
        self.change_coin_params_button.setObjectName(u"change_coin_params_button")
        self.change_coin_params_button.setGeometry(QRect(10, 10, 201, 41))
        self.tabWidget.addTab(self.coin_tab, "")
        self.coin_catalog_year_dropbox = QComboBox(self.centralwidget)
        self.coin_catalog_year_dropbox.setObjectName(u"coin_catalog_year_dropbox")
        self.coin_catalog_year_dropbox.setGeometry(QRect(1160, 415, 161, 22))
        self.video_frame = QFrame(self.centralwidget)
        self.video_frame.setObjectName(u"video_frame")
        self.video_frame.setGeometry(QRect(10, 0, 1060, 600))
        self.video_frame.setFrameShape(QFrame.Panel)
        self.video_frame.setFrameShadow(QFrame.Sunken)
        self.video_frame.setLineWidth(1)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(1090, 475, 61, 16))
        self.plainTextEdit = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(1090, 500, 231, 101))
        self.plainTextEdit.setReadOnly(True)
        self.coin_catalog_country_dropbox = QComboBox(self.centralwidget)
        self.coin_catalog_country_dropbox.setObjectName(u"coin_catalog_country_dropbox")
        self.coin_catalog_country_dropbox.setGeometry(QRect(1160, 445, 161, 22))
        self.coin_catalog_name_dropbox = QComboBox(self.centralwidget)
        self.coin_catalog_name_dropbox.setObjectName(u"coin_catalog_name_dropbox")
        self.coin_catalog_name_dropbox.setGeometry(QRect(1160, 475, 161, 22))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(1090, 420, 31, 16))
        ImageCollector.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(ImageCollector)
        self.statusbar.setObjectName(u"statusbar")
        ImageCollector.setStatusBar(self.statusbar)

        self.retranslateUi(ImageCollector)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(ImageCollector)
    # setupUi

    def retranslateUi(self, ImageCollector):
        ImageCollector.setWindowTitle(QCoreApplication.translate("ImageCollector", u"Image Collector", None))
        self.label_3.setText(QCoreApplication.translate("ImageCollector", u"Country", None))
        self.label_2.setText(QCoreApplication.translate("ImageCollector", u"Camera", None))
        self.save_photo_button.setText(QCoreApplication.translate("ImageCollector", u"New Photo", None))
        self.auto_mark_edges_checkbox.setText(QCoreApplication.translate("ImageCollector", u"auto-mark coin edges", None))
        self.new_coin_button.setText(QCoreApplication.translate("ImageCollector", u"New Coin", None))
        self.label_5.setText(QCoreApplication.translate("ImageCollector", u"Blur Kernel", None))
        self.label_6.setText(QCoreApplication.translate("ImageCollector", u"Blur Sigma", None))
        self.label_7.setText(QCoreApplication.translate("ImageCollector", u"Canny Thr 1", None))
        self.label_8.setText(QCoreApplication.translate("ImageCollector", u"Canny Thr 2", None))
        self.label_9.setText(QCoreApplication.translate("ImageCollector", u"Dilate Kernel1", None))
        self.label_10.setText(QCoreApplication.translate("ImageCollector", u"Dilate Kernel2", None))
        self.label_11.setText(QCoreApplication.translate("ImageCollector", u"Erode Kernel1", None))
        self.label_12.setText(QCoreApplication.translate("ImageCollector", u"Erode Kernel2", None))
        self.label_13.setText(QCoreApplication.translate("ImageCollector", u"Dilate Iter", None))
        self.label_14.setText(QCoreApplication.translate("ImageCollector", u"Erode Iter", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.camera_tab), QCoreApplication.translate("ImageCollector", u"Camera", None))
        self.next_gallery_photo_button.setText(QCoreApplication.translate("ImageCollector", u"Next Photo", None))
        self.previous_gallery_photo_button.setText(QCoreApplication.translate("ImageCollector", u"Previous Photo", None))
        self.redraw_coin_contour_checkbox.setText(QCoreApplication.translate("ImageCollector", u"Redraw coin contour", None))
        self.contour_correction_container.setTitle("")
        self.save_cropped_image_button.setText(QCoreApplication.translate("ImageCollector", u"Save Changes", None))
        self.automatic_contour_detextion_checkbox.setText(QCoreApplication.translate("ImageCollector", u"Automatic contour detection", None))
        self.manual_contour_reset_button.setText(QCoreApplication.translate("ImageCollector", u"Reset Manual Contour", None))
        self.label_15.setText(QCoreApplication.translate("ImageCollector", u"Blur k.", None))
        self.label_16.setText(QCoreApplication.translate("ImageCollector", u"Dilate K.1", None))
        self.label_17.setText(QCoreApplication.translate("ImageCollector", u"Dilate K.2", None))
        self.label_18.setText(QCoreApplication.translate("ImageCollector", u"Erode K.1", None))
        self.label_19.setText(QCoreApplication.translate("ImageCollector", u"Erode K.2", None))
        self.label_20.setText(QCoreApplication.translate("ImageCollector", u"Dilate I.", None))
        self.label_21.setText(QCoreApplication.translate("ImageCollector", u"Erode I.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gallery_tab), QCoreApplication.translate("ImageCollector", u"Gallery", None))
        self.remove_coin_button.setText(QCoreApplication.translate("ImageCollector", u"Remove Selected Coin", None))
        self.change_coin_params_button.setText(QCoreApplication.translate("ImageCollector", u"Change Coin Parameters", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.coin_tab), QCoreApplication.translate("ImageCollector", u"Coin ", None))
        self.label_4.setText(QCoreApplication.translate("ImageCollector", u"Coin name", None))
        self.plainTextEdit.setPlainText("")
        self.label.setText(QCoreApplication.translate("ImageCollector", u"Year", None))
    # retranslateUi

